version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-28

    steps:
        - checkout
        - run:
            name: Resolve dependencies
            command: ./gradlew app:dependencies

        - run:
            name: Assemble
            command: ./gradlew clean assembleHathorRelease -PdisablePreDex -PciBuild

        - run:
            name: Test
            command: ./gradlew testHathorRelease -PdisablePreDex
        
        - run:
            name: Lint
            command: ./gradlew ktlintCheck
